apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-role
  namespace: staging
rules:
- apiGroups: [""]
  resources: ["pods","configmaps","secrets"]
  verbs: ["get","create","delete","update"]