apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-rolebinding
  namespace: staging
subjects:
- kind: ServiceAccount
  name: dev-staging
  apiGroup: ""
roleRef:
  kind: Role
  name: dev-role
  apiGroup: rbac.authorization.k8s.io