apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: dev-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: my-container-1
        image: aputra/myapp-193:v6
        ports:
        - name: my-container-1
          containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: my-container-1
  type: NodePort
